import { useImage, rect } from '@shopify/react-native-skia';
import type { SkImage, SkRect } from '@shopify/react-native-skia';
import { useMemo } from 'react';
import type { PieceType } from '../types';

// Sprite sheet configuration
// Generated by: node scripts/generate-sprite.js
// Layout: 6x2 grid (p, n, b, r, q, k for each color)
// Row 0: white pieces, Row 1: black pieces
const SPRITE_CELL_SIZE = 128;
const SPRITE_SOURCE = require('./pieces-sprite.png');

// Piece order in sprite sheet (column index)
const PIECE_COLUMN: Record<string, number> = {
  p: 0,
  n: 1,
  b: 2,
  r: 3,
  q: 4,
  k: 5,
};

// Color row in sprite sheet
const COLOR_ROW: Record<string, number> = {
  w: 0,
  b: 1,
};

/**
 * Creates a clip rect for a piece from the sprite sheet.
 * Accepts PieceType or null (for compatibility with PieceCode from board state).
 */
export const getPieceSpriteRect = (
  pieceType: PieceType | null,
  cellSize: number = SPRITE_CELL_SIZE
): SkRect | null => {
  if (!pieceType) return null;

  const color = pieceType[0];
  const piece = pieceType[1];
  const col = PIECE_COLUMN[piece];
  const row = COLOR_ROW[color];

  if (col === undefined || row === undefined) return null;

  return rect(col * cellSize, row * cellSize, cellSize, cellSize);
};

/**
 * Hook that provides sprite sheet image and rect calculations for all pieces.
 * This is more efficient than loading 12 separate images.
 * Returns null image if sprite sheet hasn't been generated yet.
 */
export const usePieceSpriteSheet = () => {
  const image = useImage(SPRITE_SOURCE);

  const rects = useMemo(
    (): Record<PieceType, SkRect | null> => ({
      wp: rect(0, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      wn: rect(SPRITE_CELL_SIZE, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      wb: rect(SPRITE_CELL_SIZE * 2, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      wr: rect(SPRITE_CELL_SIZE * 3, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      wq: rect(SPRITE_CELL_SIZE * 4, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      wk: rect(SPRITE_CELL_SIZE * 5, 0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      bp: rect(0, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE, SPRITE_CELL_SIZE),
      bn: rect(
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE
      ),
      bb: rect(
        SPRITE_CELL_SIZE * 2,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE
      ),
      br: rect(
        SPRITE_CELL_SIZE * 3,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE
      ),
      bq: rect(
        SPRITE_CELL_SIZE * 4,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE
      ),
      bk: rect(
        SPRITE_CELL_SIZE * 5,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE,
        SPRITE_CELL_SIZE
      ),
    }),
    []
  );

  return { image, rects, cellSize: SPRITE_CELL_SIZE };
};

// Individual piece image sources (legacy - kept for compatibility)
const PIECE_SOURCES = {
  wp: require('./wp.png'),
  wn: require('./wn.png'),
  wb: require('./wb.png'),
  wr: require('./wr.png'),
  wq: require('./wq.png'),
  wk: require('./wk.png'),
  bp: require('./bp.png'),
  bn: require('./bn.png'),
  bb: require('./bb.png'),
  br: require('./br.png'),
  bq: require('./bq.png'),
  bk: require('./bk.png'),
} as const;

export type PieceImages = Record<PieceType, SkImage | null>;

export const usePieceImages = (): PieceImages => {
  const wp = useImage(PIECE_SOURCES.wp);
  const wn = useImage(PIECE_SOURCES.wn);
  const wb = useImage(PIECE_SOURCES.wb);
  const wr = useImage(PIECE_SOURCES.wr);
  const wq = useImage(PIECE_SOURCES.wq);
  const wk = useImage(PIECE_SOURCES.wk);
  const bp = useImage(PIECE_SOURCES.bp);
  const bn = useImage(PIECE_SOURCES.bn);
  const bb = useImage(PIECE_SOURCES.bb);
  const br = useImage(PIECE_SOURCES.br);
  const bq = useImage(PIECE_SOURCES.bq);
  const bk = useImage(PIECE_SOURCES.bk);

  return useMemo(
    () => ({
      wp,
      wn,
      wb,
      wr,
      wq,
      wk,
      bp,
      bn,
      bb,
      br,
      bq,
      bk,
    }),
    [wp, wn, wb, wr, wq, wk, bp, bn, bb, br, bq, bk]
  );
};

export { PIECE_SOURCES };
